# Generated by Django 4.0.3 on 2022-04-06 20:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapplicationdata',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
